@extends('layouts.site')
@section('body_class','client-portal-page')
@section('content')
@php
  $cartProducts = $products->whereIn('id', $cart->keys());
  $cartTotal = $cartProducts->sum(fn($p)=>(float)data_get($p->settings,'price',0)*(int)$cart->get($p->id));
@endphp
<section class="client-portal">
  <header class="client-portal-head"><div><span>ZONA PRIVADA</span><h1>Hola, {{ $client->name }}</h1><p>Gestioná compras, entregas y comprobantes desde un solo lugar.</p></div><form method="post" action="{{ route('client.logout') }}">@csrf<button>Salir</button></form></header>
  @if(session('success'))<div class="portal-notice">{{ session('success') }}</div>@endif
  <nav class="portal-tabs"><a href="#catalogo">Catálogo</a><a href="#carrito">Carrito <b>{{ $cart->sum() }}</b></a><a href="#pedidos">Mis pedidos</a><a href="#facturas">Facturas</a></nav>
  <section id="catalogo" class="portal-panel"><div class="portal-title"><div><span>COMPRA MAYORISTA</span><h2>Productos disponibles</h2></div><p>Los precios y descuentos se calculan según tu cuenta.</p></div><div class="portal-products">@forelse($products as $product)<article><div class="portal-product-image">@if($product->media->first()?->path)<img src="/{{ $product->media->first()->path }}" alt="">@endif</div><div><small>{{ data_get($product->settings,'code','Sin código') }}</small><h3>{{ $product->title }}</h3><strong>${{ number_format((float)data_get($product->settings,'price'),2,',','.') }}</strong></div><form method="post" action="{{ route('client.cart.add') }}">@csrf<input type="hidden" name="product_id" value="{{ $product->id }}"><input type="number" name="quantity" min="1" value="1"><button>Agregar</button></form></article>@empty<p>No hay productos con precio publicados.</p>@endforelse</div></section>
  <section id="carrito" class="portal-panel"><div class="portal-title"><div><span>PEDIDO ACTUAL</span><h2>Carrito</h2></div><strong class="portal-total">${{ number_format($cartTotal,2,',','.') }}</strong></div>@forelse($cartProducts as $product)<div class="portal-cart-row"><div><strong>{{ $product->title }}</strong><small>{{ $cart->get($product->id) }} × ${{ number_format((float)data_get($product->settings,'price'),2,',','.') }}</small></div><span>${{ number_format((float)data_get($product->settings,'price')*(int)$cart->get($product->id),2,',','.') }}</span><form method="post" action="{{ route('client.cart.remove',$product->id) }}">@csrf @method('DELETE')<button aria-label="Quitar">Quitar</button></form></div>@empty<div class="portal-empty">Tu carrito está vacío. Elegí productos del catálogo para comenzar.</div>@endforelse
  @if($cart->isNotEmpty())<form class="portal-checkout" method="post" action="{{ route('client.checkout') }}">@csrf<div><label>Entrega<select name="delivery_method"><option value="retiro">Retiro en Moldpack</option><option value="envio">Envío</option></select></label><label>Dirección de entrega<input name="delivery_address"></label></div><label>Observaciones<textarea name="notes" rows="3"></textarea></label><button>Enviar pedido</button></form>@endif</section>
  <section id="pedidos" class="portal-panel"><div class="portal-title"><div><span>SEGUIMIENTO</span><h2>Mis pedidos</h2></div></div><div class="portal-orders">@forelse($orders as $order)<article><header><div><small>{{ $order->created_at->format('d/m/Y') }}</small><h3>{{ $order->number }}</h3></div><span class="portal-status">{{ str_replace('_',' ',ucfirst($order->status)) }}</span><strong>${{ number_format($order->total,2,',','.') }}</strong></header><details><summary>Ver {{ $order->items->count() }} productos</summary>@foreach($order->items as $item)<p>{{ $item->quantity }} × {{ $item->name }} <b>${{ number_format($item->line_total,2,',','.') }}</b></p>@endforeach</details></article>@empty<div class="portal-empty">Todavía no realizaste pedidos.</div>@endforelse</div></section>
  <section id="facturas" class="portal-panel"><div class="portal-title"><div><span>DOCUMENTACIÓN</span><h2>Facturas</h2></div></div>@forelse($orders->flatMap->invoices as $invoice)<div class="portal-cart-row"><div><strong>Factura {{ $invoice->type }} {{ $invoice->number }}</strong><small>{{ optional($invoice->issued_at)->format('d/m/Y') }}</small></div><span>${{ number_format($invoice->total,2,',','.') }}</span>@if($invoice->document_path)<a href="/{{ $invoice->document_path }}" target="_blank">Descargar</a>@endif</div>@empty<div class="portal-empty">Tus comprobantes aparecerán aquí una vez emitidos.</div>@endforelse</section>
</section>
@endsection
